apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-service-deployment
  labels:
    service: books-service
    app: books-service
    tags.datadoghq.com/env: ${ENV}
    tags.datadoghq.com/service: books-service
    tags.datadoghq.com/version: ${VERSION}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-service
  template:
    metadata:
      name: books-service
      labels:
        app: books-service
        service: books-service
        tags.datadoghq.com/env: ${ENV}
        tags.datadoghq.com/service: books-service
        tags.datadoghq.com/version: ${VERSION}
        admission.datadoghq.com/enabled: "true"
        admission.datadoghq.com/config.mode: "socket"
      annotations:
        admission.datadoghq.com/js-lib.version: "v3.17.1"
        ad.datadoghq.com/books-service.logs: |
          [
            {
              "source": "nodejs",
              "service": "books-service"
            }
          ]
        ad.datadoghq.com/tags: |
          {
            "git.repository_url": "github.com/stuartcmehrens/books-service",
            "git.commit.sha": "${SHA}"
          }
    spec:
      containers:
      - name: books-service
        image: "ghcr.io/stuartcmehrens/books-service"
        ports:
        - containerPort: ${PORT}
          protocol: TCP
        env:
        - name: PORT
          value: "${PORT}"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DOGSTATSD_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_PROFILING_ENABLED
          value: "true"
        - name: DD_ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/env']
        - name: DD_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/service']
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/version']