apiVersion: v1
kind: Service
metadata:
  name: books-service-lb
  labels:
    service: books-service
    app: books-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: ${PORT}
  selector:
    app: books-service