apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-service
  labels:
    chart_name: {{ .Chart.Name }}
    chart_version: {{ .Chart.Version }}
    service: {{ .Values.service.name }}
    app: {{ .Values.service.name }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: {{ .Values.service.name }}