name: Deploy Datadog to GKE

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: gke-prod
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    - id: 'get_cluster_credentials'
      name: 'Get Cluster Credentials'
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ vars.GKE_REGION }}

    - id: 'deploy_datadog'
      name: 'Deploy Datadog'
      run: |-
        chmod +x .datadog/deploy.sh
        .datadog/deploy.sh
      env:
        DATADOG_API_KEY: ${{ secrets.DD_API_KEY }}
        DATADOG_APP_KEY: ${{ secrets.DD_APP_KEY }}
        CLUSTER_NAME: ${{ secrets.GKE_CLUSTER }}
        VALUES_FILE_PATH: .datadog/gke/values.yaml