name: Deploy to Google Cloud Run

on:
  workflow_dispatch:

env:
  REGISTRY: gcr.io

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: gcr-prod

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: |
          projects/583396614925/locations/global/workloadIdentityPools/github-actions-work-pool/providers/github-actions-provider
        service_account: github-actions-books-sa@datadog-sandbox-384117.iam.gserviceaccount.com

    - id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: books-service
        image: '${{ env.REGISTRY }}/datadog-sandbox-384117/books-service:gcr'
        env_vars: |
          DD_ENV=${{ vars.DD_ENV }}
          DD_SERVICE=books-service
          DD_VERSION=${{ github.sha }}
          DD_API_KEY=${{ secrets.DD_API_KEY }}
          DD_TRACE_ENABLED=true
          DD_LOGS_ENABLED=true
          DD_SOURCE=nodejs
          DD_LOGS_INJECTION=true
          