name: Deploy to GKE

on:
  registry_package:
    types:
    - published
    - updated
  
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: books-service-cluster

jobs:
  setup-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: us-east1

    - name: 'Deploy Datadog'
      run: |-
        helm repo add datadog https://helm.datadoghq.com
        helm repo update
        helm install datadog-deployment -f ./datadog/gke-values.yaml \
        --set datadog.apiKey=${{ secrets.DD_API_KEY }} \
        --set datadog.appKey=${{ secrets.DD_APP_KEY }} \
        --set datadog.clusterName=${{ env.GKE_CLUSTER }} \
        --version 3.10.0 \
        datadog/datadog

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        helm install books-deployment ./k8s/books-service \
        --set-string global.clusterName=${{ env.GKE_CLUSTER }} \
        --set-string global.env=dev \
        --set-string commit_sha=$GITHUB_SHA
