name: Deploy to GKE

on:
  registry_package:
    types: [published]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: books-service-cluster

jobs:
  setup-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        credentials: ${{ secrets.GKE_SA_KEY }}
        location: us-east1

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        helm dependency update ./k8s/books-service
        helm install books-deployment ./k8s/books-service \
        --set-string datadog.datadog.apiKey=${{ secrets.DD_API_KEY }} \
        --set-string datadog.datadog.appKey=${{ secrets.DD_APP_KEY }} \
        --set-string global.clusterName=${{ env.GKE_CLUSTER }} \
        --set-string global.env=dev \
        --set-string commit_sha=$GITHUB_SHA
