name: Delete GKE Autopilot Cluster

on:
  workflow_dispatch:

jobs:
  create_cluster:
    environment: gke-prod
    name: Delete Cluster
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    - id: 'setup_sdk'
      name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v1

    - id: 'delete_cluster'
      name: Run Cluster Delete Script
      run: |-
        chmod +x .gcp/gke/delete-gke-cluster.sh
        .gcp/gke/delete-gke-cluster.sh
      env:
        SA_NAME: ${{ vars.GKE_SA_NAME }}
        PROJECT_ID: ${{ secrets.GKE_PROJECT }}
        CLUSTER_NAME: ${{ secrets.GKE_CLUSTER }}
        REGION: ${{ vars.GKE_REGION }}
    