name: Deploy to GKE

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: gke-prod

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    - id: 'get_cluster_credentials'
      name: 'Get Cluster Credentials'
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ vars.GKE_REGION }}

    - name: Deploy
      run: |-
        chmod +x .gcp/gke/deploy.sh
        .gcp/gke/deploy.sh
      env:
        ENV: ${{ vars.ENV }}
        VERSION: ${{ github.sha }}
        SHA: ${{ github.sha }}
        SERVICE_FILE_PATH: ./.gcp/gke/service.yaml
        DEPLOYMENT_FILE_PATH: ./.gcp/gke/deployment.yaml
        KUBECONFIG: ${{ needs.gcloud_setup.outputs.kubeconfig }}
        PORT: 3000